apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reviews-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: book-reviews
                port:
                  number: 80
---
kind: Service
apiVersion: v1
metadata:
  name: book-reviews
spec:
  selector:
    app: book-reviews
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-reviews
  strategy:
    type: RollingUpdate
    
  template:
    metadata:
      labels:
        app: book-reviews
    spec:
      containers:
        - name: reviews
          image: afayez14/book-reviews
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: reviews-config-map
          ports:
            - containerPort: 5000
              protocol: TCP
