--- 
- name: "copy manifest files"
  copy:
    src: ~/projects/book-reviews/deploy/kube
    dest: /home/ubuntu


- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: start k3s custer
  command: k3d cluster create -p "80:80@loadbalancer" --agents 2 reviews-cluster

- name: apply k8s resources
  command: kubectl create -f /home/ubuntu/kube/configmap.yml

- name: apply deployment resource
  command: kubectl apply -f /home/ubuntu/kube/reviews.yml
